spring:
  #  cache:
  #    cache-names: countries
  #    caffeine:
  #      spec: maximumSize=500, expireAfterAccess=3s

  datasource:
    url: jdbc:postgresql://localhost:5432/lapko
    username: postgres
    password: root

  jpa:
    #    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: solko
        jdbc:
          lob:
            non_contextual_creation: true